CREATE TABLE FrontDesk(
    sin INT(11) PRIMARY KEY,
    name VARCHAR(255),
    FOREIGN KEY(sin) REFERENCES(Employee)
        ON DELETE CASCADE
    FOREIGN KEY(name) REFERENCES(Employee)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);